-- MySQL Script generated by MySQL Workbench
-- lun 03 dic 2018 17:10:27 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_giftemergency
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_giftemergency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_giftemergency` DEFAULT CHARACTER SET utf8 ;
USE `db_giftemergency` ;

-- -----------------------------------------------------
-- Table `db_giftemergency`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`images` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `file_path` TEXT NOT NULL,
  `file_name` TEXT NOT NULL,
  `file_extension` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`users` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `is_admin` TINYINT(1) NOT NULL,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `full_name` VARCHAR(51) NOT NULL,
  `phone_number` VARCHAR(10) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `photo_id` INT(13) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_images_idx` (`photo_id` ASC),
  CONSTRAINT `fk_users_images`
    FOREIGN KEY (`photo_id`)
    REFERENCES `db_giftemergency`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`questions` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(40) NOT NULL,
  `label` VARCHAR(240) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`stereotypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`stereotypes` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`answers` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `question_id` INT(13) NOT NULL,
  `slug` VARCHAR(40) NOT NULL,
  `content` VARCHAR(240) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_questions1_idx` (`question_id` ASC),
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `db_giftemergency`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`answers_stereotypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`answers_stereotypes` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `answer_id` INT(13) NOT NULL,
  `stereotype_id` INT(13) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_has_stereotypes_stereotypes1_idx` (`stereotype_id` ASC),
  INDEX `fk_answers_has_stereotypes_answers1_idx` (`answer_id` ASC),
  CONSTRAINT `fk_answers_has_stereotypes_answers1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `db_giftemergency`.`answers` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_has_stereotypes_stereotypes1`
    FOREIGN KEY (`stereotype_id`)
    REFERENCES `db_giftemergency`.`stereotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`gifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`gifts` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `stereotype_id` INT(13) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `image_id` INT(13) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_gifts_stereotypes1_idx` (`stereotype_id` ASC),
  INDEX `fk_gifts_images1_idx` (`image_id` ASC),
  CONSTRAINT `fk_gifts_stereotypes1`
    FOREIGN KEY (`stereotype_id`)
    REFERENCES `db_giftemergency`.`stereotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gifts_images1`
    FOREIGN KEY (`image_id`)
    REFERENCES `db_giftemergency`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`orders` (
  `id` INT(13) NOT NULL,
  `quantity` INT(4) NOT NULL,
  `subtotal` DECIMAL(8,2) NOT NULL,
  `iva` DECIMAL(4,2) NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_giftemergency`.`answers_stereotypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_giftemergency`.`answers_stereotypes` (
  `id` INT(13) NOT NULL AUTO_INCREMENT,
  `answer_id` INT(13) NOT NULL,
  `stereotype_id` INT(13) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_has_stereotypes_stereotypes1_idx` (`stereotype_id` ASC),
  INDEX `fk_answers_has_stereotypes_answers1_idx` (`answer_id` ASC),
  CONSTRAINT `fk_answers_has_stereotypes_answers1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `db_giftemergency`.`answers` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_has_stereotypes_stereotypes1`
    FOREIGN KEY (`stereotype_id`)
    REFERENCES `db_giftemergency`.`stereotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- ***** INITIAL VALUES *****

-- Seeding "User Photo" by default:
INSERT INTO `db_giftemergency`.`images` (`file_path`, `file_name`, `file_extension`)
		VALUES ('/public/users/img_profile', 'img_default', 'png');

-- Seeding "Admin Users":
INSERT INTO `db_giftemergency`.`users` 
	(`is_admin`,`first_name`, `last_name`, `full_name`, `photo_id`, `phone_number`, `email`, `password`)
    VALUES (1, 'Michael Brandon', 'Serrato Guerrero', 'Michael Brandon Serrato Guerrero', 1, '4422332139', 'mikebsg01@gmail.com', SHA2('hola1234', 256));
